/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as AdminWebhooksRouteImport } from './routes/admin/webhooks'
import { Route as AdminInstrumentsRouteImport } from './routes/admin/instruments'
import { Route as AdminRulesIndexRouteImport } from './routes/admin/rules.index'
import { Route as AdminRulesNewRouteImport } from './routes/admin/rules.new'
import { Route as AdminRulesIdRouteImport } from './routes/admin/rules.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminWebhooksRoute = AdminWebhooksRouteImport.update({
  id: '/webhooks',
  path: '/webhooks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminInstrumentsRoute = AdminInstrumentsRouteImport.update({
  id: '/instruments',
  path: '/instruments',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesIndexRoute = AdminRulesIndexRouteImport.update({
  id: '/rules/',
  path: '/rules/',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesNewRoute = AdminRulesNewRouteImport.update({
  id: '/rules/new',
  path: '/rules/new',
  getParentRoute: () => AdminRoute,
} as any)
const AdminRulesIdRoute = AdminRulesIdRouteImport.update({
  id: '/rules/$id',
  path: '/rules/$id',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rules/$id': typeof AdminRulesIdRoute
  '/admin/rules/new': typeof AdminRulesNewRoute
  '/admin/rules/': typeof AdminRulesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin': typeof AdminIndexRoute
  '/admin/rules/$id': typeof AdminRulesIdRoute
  '/admin/rules/new': typeof AdminRulesNewRoute
  '/admin/rules': typeof AdminRulesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/login': typeof LoginRoute
  '/admin/instruments': typeof AdminInstrumentsRoute
  '/admin/webhooks': typeof AdminWebhooksRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/rules/$id': typeof AdminRulesIdRoute
  '/admin/rules/new': typeof AdminRulesNewRoute
  '/admin/rules/': typeof AdminRulesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/admin/instruments'
    | '/admin/webhooks'
    | '/admin/'
    | '/admin/rules/$id'
    | '/admin/rules/new'
    | '/admin/rules/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/admin/instruments'
    | '/admin/webhooks'
    | '/admin'
    | '/admin/rules/$id'
    | '/admin/rules/new'
    | '/admin/rules'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/login'
    | '/admin/instruments'
    | '/admin/webhooks'
    | '/admin/'
    | '/admin/rules/$id'
    | '/admin/rules/new'
    | '/admin/rules/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/webhooks': {
      id: '/admin/webhooks'
      path: '/webhooks'
      fullPath: '/admin/webhooks'
      preLoaderRoute: typeof AdminWebhooksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/instruments': {
      id: '/admin/instruments'
      path: '/instruments'
      fullPath: '/admin/instruments'
      preLoaderRoute: typeof AdminInstrumentsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules/': {
      id: '/admin/rules/'
      path: '/rules'
      fullPath: '/admin/rules/'
      preLoaderRoute: typeof AdminRulesIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules/new': {
      id: '/admin/rules/new'
      path: '/rules/new'
      fullPath: '/admin/rules/new'
      preLoaderRoute: typeof AdminRulesNewRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/rules/$id': {
      id: '/admin/rules/$id'
      path: '/rules/$id'
      fullPath: '/admin/rules/$id'
      preLoaderRoute: typeof AdminRulesIdRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminInstrumentsRoute: typeof AdminInstrumentsRoute
  AdminWebhooksRoute: typeof AdminWebhooksRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminRulesIdRoute: typeof AdminRulesIdRoute
  AdminRulesNewRoute: typeof AdminRulesNewRoute
  AdminRulesIndexRoute: typeof AdminRulesIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminInstrumentsRoute: AdminInstrumentsRoute,
  AdminWebhooksRoute: AdminWebhooksRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminRulesIdRoute: AdminRulesIdRoute,
  AdminRulesNewRoute: AdminRulesNewRoute,
  AdminRulesIndexRoute: AdminRulesIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
